Suppress printout from importing skbuild in configure script
stanford-centaur/smt-switch pull request #323
Opened 2023-01-19 05:17 UTC by cterrill26

In response to issue [322](https://github.com/stanford-centaur/smt-switch/issues/322).

2023-01-19 06:42 UTC, yoni206 requested changes

2023-01-19 06:42 UTC, yoni206 commented on python/CMakeLists.txt
> +    import os; import sys; temp = sys.stdout; sys.stdout = open(os.devnull,\"w\"); import skbuild; sys.stdout = temp; \
Thanks for this PR! Will you be able to add a comment above this line that explains why we are doing this? something like "importing os and skbuild, while suppressing warnings from skbuild"?

2023-01-22 06:06 UTC, cterrill26 commented
Added the comment

2023-01-22 06:15 UTC, yoni206 approved these changes
Thanks for doing this!

2023-01-24 17:54 UTC, merged